<?xml version="1.0" encoding="utf-8"?><Database Name="db823292d13be1409f85a2a6bd00d88f73" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=823292d1-3be1-409f-85a2-a6bd00d88f73.sqlserver.sequelizer.com;Initial Catalog=db823292d13be1409f85a2a6bd00d88f73;Persist Security Info=True;User ID=rozsljgnpnqcnvzp" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="db823292d13be1409f85a2a6bd00d88f73ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.test" Member="test">
    <Type Name="test">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>